Pad: IOPADS_INST/PAD_clock_i S ICP
Pad: IOPADS_INST/PAD_reset_i S ICP
Pad: IOPADS_INST/PAD_boot_address0_i N ICP
Pad: IOPADS_INST/PAD_boot_address1_i N ICP
Pad: IOPADS_INST/PAD_boot_address2_i N ICP
Pad: IOPADS_INST/PAD_boot_address3_i N ICP
Pad: IOPADS_INST/PAD_boot_address4_i N ICP
Pad: IOPADS_INST/PAD_boot_address5_i N ICP
Pad: IOPADS_INST/PAD_boot_address6_i N ICP
Pad: IOPADS_INST/PAD_boot_address7_i N ICP
Pad: IOPADS_INST/PAD_boot_address8_i N ICP
Pad: IOPADS_INST/PAD_boot_address9_i N ICP
Pad: IOPADS_INST/PAD_boot_address10_i N ICP
Pad: IOPADS_INST/PAD_boot_address11_i N ICP
Pad: IOPADS_INST/PAD_boot_address12_i N ICP
Pad: IOPADS_INST/PAD_boot_address13_i N ICP
Pad: IOPADS_INST/PAD_boot_address14_i N ICP
Pad: IOPADS_INST/PAD_boot_address15_i N ICP
Pad: IOPADS_INST/PAD_boot_address16_i N ICP
Pad: IOPADS_INST/PAD_boot_address17_i N ICP
Pad: IOPADS_INST/PAD_boot_address18_i N ICP
Pad: IOPADS_INST/PAD_boot_address19_i N ICP
Pad: IOPADS_INST/PAD_boot_address20_i N ICP
Pad: IOPADS_INST/PAD_boot_address21_i N ICP
Pad: IOPADS_INST/PAD_boot_address22_i N ICP
Pad: IOPADS_INST/PAD_boot_address23_i N ICP
Pad: IOPADS_INST/PAD_boot_address24_i N ICP
Pad: IOPADS_INST/PAD_boot_address25_i N ICP
Pad: IOPADS_INST/PAD_boot_address26_i N ICP
Pad: IOPADS_INST/PAD_boot_address27_i N ICP
Pad: IOPADS_INST/PAD_boot_address28_i N ICP
Pad: IOPADS_INST/PAD_boot_address29_i N ICP
Pad: IOPADS_INST/PAD_boot_address30_i N ICP
Pad: IOPADS_INST/PAD_boot_address31_i N ICP
Pad: IOPADS_INST/PAD_instruction_address0_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address1_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address2_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address3_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address4_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address5_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address6_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address7_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address8_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address9_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address10_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address11_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address12_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address13_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address14_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address15_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address16_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address17_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address18_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address19_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address20_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address21_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address22_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address23_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address24_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address25_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address26_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address27_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address28_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address29_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address30_o S BD8P
Pad: IOPADS_INST/PAD_instruction_address31_o S BD8P
Pad: IOPADS_INST/PAD_instruction_in0_i W ICP
Pad: IOPADS_INST/PAD_instruction_in1_i W ICP
Pad: IOPADS_INST/PAD_instruction_in2_i W ICP
Pad: IOPADS_INST/PAD_instruction_in3_i W ICP
Pad: IOPADS_INST/PAD_instruction_in4_i W ICP
Pad: IOPADS_INST/PAD_instruction_in5_i W ICP
Pad: IOPADS_INST/PAD_instruction_in6_i W ICP
Pad: IOPADS_INST/PAD_instruction_in7_i W ICP
Pad: IOPADS_INST/PAD_instruction_in8_i W ICP
Pad: IOPADS_INST/PAD_instruction_in9_i W ICP
Pad: IOPADS_INST/PAD_instruction_in10_i W ICP
Pad: IOPADS_INST/PAD_instruction_in11_i W ICP
Pad: IOPADS_INST/PAD_instruction_in12_i W ICP
Pad: IOPADS_INST/PAD_instruction_in13_i W ICP
Pad: IOPADS_INST/PAD_instruction_in14_i W ICP
Pad: IOPADS_INST/PAD_instruction_in15_i W ICP
Pad: IOPADS_INST/PAD_instruction_in16_i W ICP
Pad: IOPADS_INST/PAD_instruction_in17_i W ICP
Pad: IOPADS_INST/PAD_instruction_in18_i W ICP
Pad: IOPADS_INST/PAD_instruction_in19_i W ICP
Pad: IOPADS_INST/PAD_instruction_in20_i W ICP
Pad: IOPADS_INST/PAD_instruction_in21_i W ICP
Pad: IOPADS_INST/PAD_instruction_in22_i W ICP
Pad: IOPADS_INST/PAD_instruction_in23_i W ICP
Pad: IOPADS_INST/PAD_instruction_in24_i W ICP
Pad: IOPADS_INST/PAD_instruction_in25_i W ICP
Pad: IOPADS_INST/PAD_instruction_in26_i W ICP
Pad: IOPADS_INST/PAD_instruction_in27_i W ICP
Pad: IOPADS_INST/PAD_instruction_in28_i W ICP
Pad: IOPADS_INST/PAD_instruction_in29_i W ICP
Pad: IOPADS_INST/PAD_instruction_in30_i W ICP
Pad: IOPADS_INST/PAD_instruction_in31_i W ICP
Pad: IOPADS_INST/PAD_data_rw_address0_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address1_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address2_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address3_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address4_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address5_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address6_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address7_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address8_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address9_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address10_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address11_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address12_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address13_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address14_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address15_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address16_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address17_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address18_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address19_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address20_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address21_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address22_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address23_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address24_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address25_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address26_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address27_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address28_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address29_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address30_o E BD8P
Pad: IOPADS_INST/PAD_data_rw_address31_o E BD8P
Pad: IOPADS_INST/PAD_data_out0_o E BD8P
Pad: IOPADS_INST/PAD_data_out1_o E BD8P
Pad: IOPADS_INST/PAD_data_out2_o E BD8P
Pad: IOPADS_INST/PAD_data_out3_o E BD8P
Pad: IOPADS_INST/PAD_data_out4_o E BD8P
Pad: IOPADS_INST/PAD_data_out5_o E BD8P
Pad: IOPADS_INST/PAD_data_out6_o E BD8P
Pad: IOPADS_INST/PAD_data_out7_o E BD8P
Pad: IOPADS_INST/PAD_data_out8_o E BD8P
Pad: IOPADS_INST/PAD_data_out9_o E BD8P
Pad: IOPADS_INST/PAD_data_out10_o E BD8P
Pad: IOPADS_INST/PAD_data_out11_o E BD8P
Pad: IOPADS_INST/PAD_data_out12_o E BD8P
Pad: IOPADS_INST/PAD_data_out13_o E BD8P
Pad: IOPADS_INST/PAD_data_out14_o E BD8P
Pad: IOPADS_INST/PAD_data_out15_o E BD8P
Pad: IOPADS_INST/PAD_data_out16_o E BD8P
Pad: IOPADS_INST/PAD_data_out17_o E BD8P
Pad: IOPADS_INST/PAD_data_out18_o E BD8P
Pad: IOPADS_INST/PAD_data_out19_o E BD8P
Pad: IOPADS_INST/PAD_data_out20_o E BD8P
Pad: IOPADS_INST/PAD_data_out21_o E BD8P
Pad: IOPADS_INST/PAD_data_out22_o E BD8P
Pad: IOPADS_INST/PAD_data_out23_o E BD8P
Pad: IOPADS_INST/PAD_data_out24_o E BD8P
Pad: IOPADS_INST/PAD_data_out25_o E BD8P
Pad: IOPADS_INST/PAD_data_out26_o E BD8P
Pad: IOPADS_INST/PAD_data_out27_o E BD8P
Pad: IOPADS_INST/PAD_data_out28_o E BD8P
Pad: IOPADS_INST/PAD_data_out29_o E BD8P
Pad: IOPADS_INST/PAD_data_out30_o E BD8P
Pad: IOPADS_INST/PAD_data_out31_o E BD8P
Pad: IOPADS_INST/PAD_data_write_request_o W BD8P
Pad: IOPADS_INST/PAD_data_write_mask0_o N BD8P
Pad: IOPADS_INST/PAD_data_write_mask1_o N BD8P
Pad: IOPADS_INST/PAD_data_write_mask2_o N BD8P
Pad: IOPADS_INST/PAD_data_write_mask3_o N BD8P
Pad: IOPADS_INST/PAD_data_in0_i W ICP
Pad: IOPADS_INST/PAD_data_in1_i W ICP
Pad: IOPADS_INST/PAD_data_in2_i W ICP
Pad: IOPADS_INST/PAD_data_in3_i W ICP
Pad: IOPADS_INST/PAD_data_in4_i W ICP
Pad: IOPADS_INST/PAD_data_in5_i W ICP
Pad: IOPADS_INST/PAD_data_in6_i W ICP
Pad: IOPADS_INST/PAD_data_in7_i W ICP
Pad: IOPADS_INST/PAD_data_in8_i W ICP
Pad: IOPADS_INST/PAD_data_in9_i W ICP
Pad: IOPADS_INST/PAD_data_in10_i W ICP
Pad: IOPADS_INST/PAD_data_in11_i W ICP
Pad: IOPADS_INST/PAD_data_in12_i W ICP
Pad: IOPADS_INST/PAD_data_in13_i W ICP
Pad: IOPADS_INST/PAD_data_in14_i W ICP
Pad: IOPADS_INST/PAD_data_in15_i W ICP
Pad: IOPADS_INST/PAD_data_in16_i W ICP
Pad: IOPADS_INST/PAD_data_in17_i W ICP
Pad: IOPADS_INST/PAD_data_in18_i W ICP
Pad: IOPADS_INST/PAD_data_in19_i W ICP
Pad: IOPADS_INST/PAD_data_in20_i W ICP
Pad: IOPADS_INST/PAD_data_in21_i W ICP
Pad: IOPADS_INST/PAD_data_in22_i W ICP
Pad: IOPADS_INST/PAD_data_in23_i W ICP
Pad: IOPADS_INST/PAD_data_in24_i W ICP
Pad: IOPADS_INST/PAD_data_in25_i W ICP
Pad: IOPADS_INST/PAD_data_in26_i W ICP
Pad: IOPADS_INST/PAD_data_in27_i W ICP
Pad: IOPADS_INST/PAD_data_in28_i W ICP
Pad: IOPADS_INST/PAD_data_in29_i W ICP
Pad: IOPADS_INST/PAD_data_in30_i W ICP
Pad: IOPADS_INST/PAD_data_in31_i W ICP
Pad: IOPADS_INST/PAD_interrupt_request_external_i N ICP
Pad: IOPADS_INST/PAD_interrupt_request_timer_i N ICP
Pad: IOPADS_INST/PAD_interrupt_request_software_i N ICP




Pad: IOPADS_INST/PAD_vdd_E E VDDORPADP
Pad: IOPADS_INST/PAD_vdd_core_E E VDDPADP
Pad: IOPADS_INST/PAD_vdd_core_N N VDDPADP
Pad: IOPADS_INST/PAD_vss_core_N N GNDORPADP
Pad: IOPADS_INST/PAD_vss_W W GNDORPADP
Pad: IOPADS_INST/PAD_vss_S S GNDORPADP

Pad: IOPADS_INST/PAD_corner_lr SE CORNERP
Pad: IOPADS_INST/PAD_corner_ll SW CORNERP
Pad: IOPADS_INST/PAD_corner_ur NE CORNERP
Pad: IOPADS_INST/PAD_corner_ul NW CORNERP

